<?php $this->htmlElement('body')->appendAttribute('class', 'columbo show');
$this->headScript()->appendFile($this->assetUrl('js/download-button.js', 'Columbo'));
?>
<?= $this->pageTitle('Columb\'O') ?>

<?php
$sectionNavs = [
    'columbo-disk' => $this->translate('Disk usage'),
];

echo $this->sectionNav($sectionNavs, 'view.show.section_nav');
?>

<div id="columbo-disk" class="active section">
<h2><?= $this->translate('Disk usage') ?></h2>

<table class="tablesaw tablesaw-stack">
    <thead>
        <tr>
            <th><?= $this->translate('Total media size'); ?></th>
            <th><?= $this->translate('Total assets size'); ?></th>
            <th><?= $this->translate('Total /files size'); ?></th>
            <th><?= $this->translate('Total /files + media'); ?></th>
            <th><?= $this->translate('Total omeka install size'); ?></th>
        </tr>
    </thead>
    <tbody>
            <td><?= $this->escapeHtml($installSize['totalMedia']) ?></td>
            <td><?= $this->escapeHtml($installSize['totalAssets']) ?></td>
            <td><?= $this->escapeHtml($installSize['totalFiles']) ?></td>
            <td><?= $this->escapeHtml($installSize['total']) ?></td>
            <td><?= $this->escapeHtml($installSize['omeka']) ?></td>
    </tbody>
</table>

<?php
$this->headScript()->captureStart();
?>
  document.addEventListener('DOMContentLoaded', function() {
    addCsvDownloadButton('columbo-disk');
  });
<?php
$this->headScript()->captureEnd();
?>