function addCsvDownloadButton(divId) {
  
  // Code generated by an AI.
  // It simply finds the closest "table" to the div with divId id
  // and exports it as CSV.

  const container = document.getElementById(divId);
  if (!container) return;

  const table = container.querySelector('table');
  if (!table) return;

  // Create button
  const btn = document.createElement('button');
  btn.textContent = 'Download CSV';
  btn.classList.add('download-csv-btn'); // style via CSS if desired
  btn.addEventListener('click', () => {
    let csv = [];
    for (const row of table.querySelectorAll('tr')) {
      const cols = Array.from(row.querySelectorAll('th, td')).map(col => {
        let text = col.innerText.replace(/"/g, '""');
        if (text.search(/("|,|\n)/g) >= 0) text = `"${text}"`;
        return text;
      });
      csv.push(cols.join(','));
    }

    const blob = new Blob([csv.join('\n')], { type: 'text/csv;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = divId + '.csv';
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  });

  container.appendChild(btn);
}
